# Generated by Django 5.1.1 on 2024-11-07 20:05

import admin_panel.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRegister',
            fields=[
                ('admin_id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('company_abn', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(default=admin_panel.models.generate_category_id, editable=False, max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the category', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_id', models.ForeignKey(blank=True, help_text='Admin who created or last modified this category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.adminregister')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('admin_id', 'category_id')},
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('subcategory_id', models.CharField(default=admin_panel.models.generate_subcategory_id, editable=False, max_length=2, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the subcategory', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_id', models.ForeignKey(blank=True, help_text='Admin who created or last modified this subcategory', null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.adminregister')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='admin_panel.category')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('admin_id', 'category', 'subcategory_id')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the product', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(help_text='Number of items available in stock')),
                ('size', models.CharField(blank=True, help_text='Size of the product (e.g., Small, Medium, Large)', max_length=50, null=True)),
                ('image_1', models.ImageField(blank=True, help_text='Primary image of the product', null=True, upload_to='products/')),
                ('image_2', models.ImageField(blank=True, help_text='Secondary image of the product', null=True, upload_to='products/')),
                ('image_3', models.ImageField(blank=True, help_text='Tertiary image of the product', null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_id', models.ForeignKey(blank=True, help_text='Admin who created or last modified this product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.adminregister')),
                ('category', models.ForeignKey(help_text='Category to which the product belongs', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='admin_panel.category')),
                ('subcategory', models.ForeignKey(help_text='Subcategory to which the product belongs', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='admin_panel.subcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
