# Generated by Django 5.1.1 on 2024-10-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_category_subcategory_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminregister',
            name='id',
        ),
        migrations.AlterField(
            model_name='adminregister',
            name='admin_id',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
