# Generated by Django 5.1.1 on 2024-10-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_adminregister_id_alter_adminregister_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='Size of the product (e.g., Small, Medium, Large)', max_length=50, null=True),
        ),
    ]
