# Generated by Django 5.1.2 on 2024-11-05 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userpanel', '0001_initial'),
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='customuser_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='Userpanel.customuser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='admin_panel.product')),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='Userpanel.customuser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='admin_panel.product')),
            ],
        ),
    ]
