# Generated by Django 5.1.2 on 2024-11-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userpanel', '0002_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sub_total',
            field=models.IntegerField(),
        ),
    ]
