branch-defaults:
  default:
    environment: Trendweave-users-dev
    group_suffix: null
global:
  application_name: Trendweave_users
  branch: null
  default_ec2_keyname: userpanel
  default_platform: Python 3.9 running on 64bit Amazon Linux 2023
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
